import argparse
import json
import sys
try:
    import requests
except ImportError:
    import urllib.request as requests # Minimal fallback if needed, but requests is expected
from pathlib import Path
from typing import List, Set

# --- CONFIGURATION ---
OUTPUT_FILE = "seed_topics.txt"
GOOGLE_TAXONOMY_URL = "http://www.google.com/basepages/producttype/taxonomy.en-US.txt"
OLLAMA_URL = "http://127.0.0.1:11434/api/generate"
DEFAULT_MODEL = "llama3.2:3b"


class SeedFactory:
    def __init__(self, output_path: str = OUTPUT_FILE):
        self.output_path = Path(output_path)
        self.seeds: Set[str] = set()

    def load_existing(self):
        if self.output_path.exists():
            with open(self.output_path, "r", encoding="utf-8") as f:
                for line in f:
                    t = line.strip()
                    if t and not t.startswith("#"):
                        self.seeds.add(t)

    def save(self):
        sorted_seeds = sorted(list(self.seeds))
        with self.output_path.open("w", encoding="utf-8") as f:
            f.write("# Generated by SeedFactory\n")
            for s in sorted_seeds:
                f.write(f"{s}\n")
        print(f"[SUCCESS] Saved {len(sorted_seeds)} seeds to {self.output_path}")

    def harvest_google_taxonomy(self):
        print(f"[INFO] Harvesting from Google Shopping Taxonomy...")
        try:
            r = requests.get(GOOGLE_TAXONOMY_URL)
            r.raise_for_status()
            lines = r.text.splitlines()
            for line in lines:
                if not line or line.startswith("#"):
                    continue
                parts = line.split(">")
                leaf = parts[-1].strip().lower().replace(" & ", " ").replace(",", "")
                if len(leaf) > 3:
                    self.seeds.add(leaf)
        except Exception as e:
            print(f"[ERROR] Google taxonomy harvest failed: {e}")

    def brainstorm_llm(self, topic: str, count: int = 10, model: str = DEFAULT_MODEL):
        print(f"[INFO] Brainstorming sub-niches for '{topic}' using LLM ({model})...")
        prompt = f"""
        Act as a market research expert. Brainstorm {count} specific sub-niches or product categories for the broad topic: "{topic}".
        Return ONLY a JSON list of strings. No preamble, no explanation.
        Example: ["mechanical keyboards", "ergonomic mice", "monitor arms"]
        """
        try:
            r = requests.post(
                OLLAMA_URL,
                json={
                    "model": model,
                    "prompt": prompt,
                    "format": "json",
                    "stream": False
                },
                timeout=60
            )
            r.raise_for_status()
            response_json = r.json()
            response_text = response_json.get("response", "[]")
            new_seeds = json.loads(response_text)
            items = []
            if isinstance(new_seeds, list):
                items = new_seeds
            elif isinstance(new_seeds, dict):
                # Handle cases where the model wraps the list in an object key
                for value in new_seeds.values():
                    if isinstance(value, list):
                        items.extend(value)
            
            for s in items:
                if isinstance(s, str):
                    self.seeds.add(s.lower().strip())
                    print(f"  + Added: {s}")
        except Exception as e:
            print(f"[ERROR] LLM brainstorming failed: {e}")


def main():
    parser = argparse.ArgumentParser(description="Universal Seed Factory - Generate niche topics.")
    parser.add_argument("--source", choices=["google", "llm", "manual"], default="manual", help="Source of seeds")
    parser.add_argument("--topic", help="Topic for LLM brainstorming")
    parser.add_argument("--count", type=int, default=10, help="Number of seeds to brainstorm")
    parser.add_argument("--append", action="store_true", help="Append to existing seeds instead of overwriting")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="Ollama model to use")

    args = parser.parse_args()
    factory = SeedFactory()

    if args.append:
        factory.load_existing()

    before = set(factory.seeds)

    if args.source == "google":
        factory.harvest_google_taxonomy()
    elif args.source == "llm":
        if not args.topic:
            print("[ERROR] --topic is required for LLM source.")
            return 2
        factory.brainstorm_llm(args.topic, count=args.count, model=args.model)

    if args.source in {"google", "llm"} and factory.seeds == before:
        print("[ERROR] Seed generation produced no new seeds; preserving existing seed_topics.txt.")
        return 1

    factory.save()
    return 0


if __name__ == "__main__":
    sys.exit(main())
